version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend-evolua"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/backend-evolua/backend-evolua"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
