// Dashboard components — barrel export
export { DashboardSidebar } from "./dashboard-sidebar"
export { DashboardHeader } from "./dashboard-header"
export { WelcomeSection } from "./welcome-section"
export { StatsCards } from "./stats-cards"
export { QuickActionsSidebar } from "./quick-actions-sidebar"
export { WeeklyAgenda } from "./weekly-agenda"
export { AIAssistantPanel } from "./ai-assistant-panel"
export { QuickNotes } from "./quick-notes"
export { RecentDocuments } from "./recent-documents"
export { ScheduleCard } from "./schedule-card"
export { QuickActionsBar } from "./quick-actions-bar"
export { DashboardMiniCalendar } from "./dashboard-mini-calendar"
export { RecentPatients } from "./recent-patients"
export { RemindersPanel } from "./reminders-panel"
export { DashboardTodoList } from "./dashboard-todo-list"
export { LogoutButton } from "./logout-button"
export { NotificationPanel, useNotifications } from "./notification-panel"
